My Project: SHELL
SHELL
Functions
static char * _strtok (char *str, const char *delim, char **saveptr)
static void usage (BaseSequentialStream *chp, char *p)
static void list_commands (BaseSequentialStream *chp, const ShellCommand *scp)
static void cmd_info (BaseSequentialStream *chp, int argc, char *argv[])
static void cmd_systime (BaseSequentialStream *chp, int argc, char *argv[])
static bool cmdexec (const ShellCommand *scp, BaseSequentialStream *chp, char *name, int argc, char *argv[])
static THD_FUNCTION (shell_thread, p)
Shell thread function.
void shellInit (void)
Shell manager initialization.
void shellExit (msg_t msg)
Terminates the shell.
thread_t * shellCreateStatic (const ShellConfig *scp, void *wsp, size_t size, tprio_t prio)
Spawns a new shell.
bool shellGetLine (BaseSequentialStream *chp, char *line, unsigned size)
Reads a whole line from the input channel.
Variables
event_source_t shell_terminated
Shell termination event source.
static ShellCommand local_commands []
Array of the default commands.
Detailed Description
Function Documentation
_strtok()
static char* _strtok (char * str, const char * delim, char ** saveptr) static
Definition at line 37 of file shell.c.
Referenced by THD_FUNCTION().
usage()
static void usage (BaseSequentialStream * chp, char * p) static
Definition at line 54 of file shell.c.
Referenced by cmd_info(), cmd_systime(), and THD_FUNCTION().
list_commands()
static void list_commands (BaseSequentialStream * chp, const ShellCommand * scp) static
Definition at line 59 of file shell.c.
Referenced by THD_FUNCTION().
cmd_info()
static void cmd_info (BaseSequentialStream * chp, int argc, char * argv[]) static
Definition at line 67 of file shell.c.
References usage().
cmd_systime()
static void cmd_systime (BaseSequentialStream * chp, int argc, char * argv[]) static
Definition at line 99 of file shell.c.
References usage().
cmdexec()
static bool cmdexec (const ShellCommand * scp, BaseSequentialStream * chp, char * name, int argc, char * argv[]) static
Definition at line 118 of file shell.c.
Referenced by THD_FUNCTION().
THD_FUNCTION()
static THD_FUNCTION (shell_thread , p) static
Shell thread function.
Parameters
[in] p pointer to a BaseSequentialStream object
Definition at line 136 of file shell.c.
References _strtok(), cmdexec(), list_commands(), local_commands, shellExit(), shellGetLine(), and usage().
shellInit()
void shellInit (void)
Shell manager initialization.
@api
Definition at line 197 of file shell.c.
References shell_terminated.
Referenced by main().
shellExit()
void shellExit (msg_t msg)
Terminates the shell.
Note
Must be invoked from the command handlers.
Does not return.
Parameters
[in] msg shell exit code
@api
Definition at line 211 of file shell.c.
References shell_terminated.
Referenced by THD_FUNCTION().
shellCreateStatic()
thread_t* shellCreateStatic (const ShellConfig * scp, void * wsp, size_t size, tprio_t prio)
Spawns a new shell.
Precondition
CH_CFG_USE_HEAP and CH_CFG_USE_DYNAMIC must be enabled.
Parameters
[in] scp pointer to a ShellConfig object
[in] size size of the shell working area to be allocated
[in] prio priority level for the new shell
Returns
A pointer to the shell thread.
Return values
NULL thread creation failed because memory allocation.
@api
Create statically allocated shell thread.
Parameters
[in] scp pointer to a ShellConfig object
[in] wsp pointer to a working area dedicated to the shell thread stack
[in] size size of the shell working area
[in] prio priority level for the new shell
Returns
A pointer to the shell thread.
@api
Definition at line 250 of file shell.c.
shellGetLine()
bool shellGetLine (BaseSequentialStream * chp, char * line, unsigned size)
Reads a whole line from the input channel.
Parameters
[in] chp pointer to a BaseSequentialStream object
[in] line pointer to the line buffer
[in] size buffer maximum length
Returns
The operation status.
Return values
true the channel was reset or CTRL-D pressed.
false operation successful.
@api
Definition at line 268 of file shell.c.
Referenced by THD_FUNCTION().
Variable Documentation
shell_terminated
event_source_t shell_terminated
Shell termination event source.
Definition at line 35 of file shell.c.
Referenced by shellExit(), and shellInit().
local_commands
ShellCommand local_commands[] static
Initial value:
= {
  {"info", cmd_info},
  {"systime", cmd_systime},
  {NULL, NULL}
}
Array of the default commands.
Definition at line 112 of file shell.c.
Referenced by THD_FUNCTION().